spring:
  cloud:
    gateway:
      routes:
        - id: swiggy-app
          uri: lb://SWIGGY-APP
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthenticationFilter
          # ????? SWIGGY-APP ?????????? (lb)
          # ????? /swiggy/** ??????
          # ?????? AuthenticationFilter ???
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter
          # ????? RESTAURANT-SERVICE ?????????? (lb)
          # ????? /restaurant/** ??????
          # ?????? AuthenticationFilter ???
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**
          # ????? IDENTITY-SERVICE ?????????? (lb)
          # ????? /auth/** ??????
    consul:
      host: localhost           # Consul ?????????????
      port: 8500                # Consul ???????? 8500
      discovery:
        enabled: true           # ?? Consul ????
        register: true          # ????????? Consul
        prefer-ip-address: true # ?? IP ??????
        health-check-interval: 30s # ???????????? 30 ?
application:
  name: SWIGGY-GATEWAY           # ?????????? SWIGGY-GATEWAY
