spring:
  cloud:
    consul:
      host: localhost           # Consul ?????????????
      port: 8500                # Consul ???????? 8500
      discovery:
        enabled: true           # ?? Consul ????
        register: true          # ????????? Consul
        prefer-ip-address: true # ?? IP ??????
        health-check-interval: 30s # ???????????? 30 ?
server:
  port: 8761                    # ????????