server:
  port: 8081

spring:
  application:
    name: SWIGGY-APP

spring.cloud.consul:
  host: localhost  # Consul ????? IP ??
  port: 8500       # Consul ???????????????????

eureka:
  client:
    enabled: false  # ?? Eureka ???????? Consul
