server:
  port: 8081  # ?????????? 8081

spring:
  config:
    import: "consul:"  # ?? Consul ??
  application:
    name: SWIGGY-APP  # ????????? SWIGGY-APP
  cloud:
    consul:
      host: localhost  # Consul ????? IP ??
      port: 8500       # Consul ???????????????????
      discovery:
        enabled: true  # ?? Consul ????
        register: true  # ????????? Consul
        prefer-ip-address: true  # ?? IP ??????
        healthCheck:
          enabled: true  # ??????
          interval: 10s  # ??????? 10 ?
          timeout: 5s  # ??????? 5 ?
    config:
      enabled: true  # ?? Consul ??
      import-check:
        enabled: false  # ??????
eureka:
  client:
    enabled: false  # ?? Eureka ???????? Consul

management:
  endpoints:
    web:
      exposure:
        include: health  # ????????
  endpoint:
    health:
      show-details: always  # ????????????